### ISSUE TITLE
http basic auth

### ISSUE THREAD

**Issue by so0k** [vivekjuneja/docker_registry_cli#3]
I tried running this searching a v2 registry behind http basic auth, but it didn't seem to work?

```
$ docker run -it --rm docker-registry-cli:latest-slim bash
$ root@d536269dda11:/usr/src/app# python browser.py
Usage: browser.py <registry_endpoint> <keyword> <values>
 valid keywords : search, list, gettag
$ root@d536269dda11:/usr/src/app# python browser.py user:password@registry.mysite.com search busybox
Traceback (most recent call last):
  File "browser.py", line 72, in <module>
    search_for_repo(regurl, repo_to_search)
  File "browser.py", line 16, in search_for_repo
    repo_array = get_all_repos(url);
  File "browser.py", line 8, in get_all_repos
    parsed_json = json.loads(req.text)
  File "/usr/local/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)
```

**Comment by vivekjuneja** [comment]
Thanks @so0k for finding this. Let me check with basic auth and revert to you on this.

**Comment by vivekjuneja** [comment]
@so0k  - Are you using HTTPS or HTTP for the Docker registry ?

**Comment by vivekjuneja** [comment]
The issue is that I was making a non-Auth based Request to the Registry API. I have modified it to include a flag for auth / no-auth and ssl / no-ssl. This will help with the case you mentioned. 

I am releasing that change on a branch in a bit. 

Thanks again for your pull.

**Comment by so0k** [comment]
sorry, didn't see your replies. Using HTTP basic auth at the moment (no ssl cert).

**Comment by vivekjuneja** [comment]
@so0k  - You can use the `auth_ssl_support` branch to test the capability to support authenticated and ssl based registry'. 

Sample commands:-
1. Non-Auth and Non-SSL

`python browser.py 192.168.59.103:5000 search busy`
1. Auth and Non-SSL

`python browser.py exampleuser:exampleuser@192.168.59.103:443 search busybox auth`
1. Auth and SSL

`python browser.py exampleuser:exampleuser@192.168.59.103:443 search mobile busybox ssl`

**Comment by so0k** [comment]
just tested, seems to work:

``` console
/usr/src/app # python browser.py user:pw@registry.mysite.com list all

-----------
1) Name: test/api
Tags: latest
-----------
2) Name: test/worker
Tags: latest
-----------
...
```

or via docker:
`docker run --rm docker-registry-cli:latest-alpine user:pw@registry.mysite.com search busybox`

**Comment by vivekjuneja** [comment]
Thanks @so0k. I am working on Test cases for this case. That'll help it have some coverage.
