### ISSUE TITLE
ImportError: No module named flask

### ISSUE THREAD

**Issue by kushalgangan** [vivekjuneja/docker_registry_cli#9]
while running commands with ssl failing as below :

python browser_web.py localhost python browser_web.py localhost ssl
Traceback (most recent call last):
  File "browser_web.py", line 3, in <module>
    from flask import Flask
ImportError: No module named flask

**Comment by vivekjuneja** [comment]
Please install the dependencies as in the file `requirements.txt`

You can perform ` pip install -r requirements.txt` to install the missing modules.
